version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - postgres_/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/botdb
      BOT_TOKEN: your_bot_token
      BOT_NAME: your_bot_name
    ports:
      - "8080:8080"

volumes:
  postgres_